import type { ArticleDraft } from "../article.js";
import type {
  GenerationRequest,
  GenerationResult,
  LLMProvider,
  TranslationRequest,
  TranslationResult,
} from "./types.js";

/**
 * Offline provider: deterministic output, no model call, no API key, no cost.
 * Exercises the whole pipeline (research → synthesis → dedup → translation →
 * write). It deliberately has NO judgeSameEvent, so the dedup gray zone falls
 * back to the conservative "treat as duplicate" path.
 */
export function createMockProvider(): LLMProvider {
  return {
    name: "mock",

    async generate(req: GenerationRequest): Promise<GenerationResult> {
      const category = req.categories[0] ?? "news";
      const sources = req.sources.length
        ? req.sources.map((s) => s.url)
        : ["https://example.com/test-source"];

      const body = [
        "This article is a **deterministic draft** produced by the `mock` provider, without calling any model. It exists to verify the pipeline end to end.",
        "",
        "## Context",
        "",
        req.sources.length
          ? `The material comes from ${req.sources.length} source(s) fetched by the pipeline.`
          : "No sources were fetched: this is pure placeholder content.",
        "",
        "## Details",
        "",
        "The body is English Markdown with subheadings, so it exercises the theme's rendering (prose, components) like a real article.",
      ].join("\n");

      const draft: ArticleDraft = {
        title: "Test draft from the NewsForge pipeline",
        description:
          "Placeholder article generated by the mock provider to validate the chain without cost or API key.",
        category,
        body,
        sources,
      };

      return { draft, usage: { inputTokens: 0, outputTokens: 0 } };
    },

    async translate(req: TranslationRequest): Promise<TranslationResult> {
      // Marked, not translated: enough to verify per-locale file writing offline.
      return {
        title: `[mock-translation] ${req.title}`,
        description: `[mock-translation] ${req.description}`,
        body: req.body,
        usage: { inputTokens: 0, outputTokens: 0 },
      };
    },
  };
}
